baseURL = 'http://www.fairplayers.fr'
defaultContentLanguage = "fr"
enableRobotsTXT = true
languageCode = 'fr-fr'
resourceDir = "../resources"
summaryLength = 30
theme = ["github.com/half-duplex/hugo-arcana"]
title = 'fairplayers'

[pagination]
  disableAliases = false
  pagerSize = 10
  path = 'page'

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[taxonomies]
  category = 'categories'
  tag = 'tags'

[params]
    description = "Association de joueurs et joueuses de jeux vidéo - Betton"
    # show_post_dates = false

    [[params.social]]
        title = "Discord"
        icon = "fa-discord"
        url = "https://discord.gg/Cxy7tW4M46"
    [[params.social]]
        title = "Twitch"
        icon = "fa-twitch"
        url = "https://www.twitch.tv/fairplayersfr"
    [[params.social]]
        title = "Instagram"
        icon = "fa-instagram"
        url = "https://www.instagram.com/fairplayersfr"
    [[params.social]]
        title = "Youtube"
        icon = "fa-youtube"
        url = "https://www.youtube.com/@fairplayersfr"
    [[params.social]]
        title = "Mastodon"
        icon = "fa-mastodon"
        url = "https://piaille.fr/@fairplayers"
    [[params.social]]
        title = "Github"
        icon = "fa-github"
        url = "https://github.com/fairplayers"

    [params.footer]

        [[params.footer.links]]
            header = "Evènements"
        [[params.footer.links.links]]
            title = "Écran partagé: Minecraft"
            url = "/article/retour-ecran-partage-minecraft/"
        [[params.footer.links.links]]
            title = "Faites des Jeux 2024"
            url = "/article/faites-des-jeux-2024/"
        [[params.footer.links.links]]
            title = "Écran partagé: Knit's Island"
            url = "/article/ecran-partage-knit-s-island/"
        [[params.footer.links.links]]
            title = "Faites des Jeux 2023"
            url = "/article/retour-faites-des-jeux-2023/"
        [[params.footer.links.links]]
            title = "Tournoi Just Dance"
            url = "/article/retour-tournoi-just-dance/"
        [[params.footer.links.links]]
            title = "Stunfest 2023"
            url = "/article/retour-stunfest-2023/"
        [[params.footer.links.links]]
            title = "Rétrogaming au centre de loisirs"
            url = "/article/retrogaming-centre-loisirs-betton/"

        [[params.footer.links]]
            header = "LAN"
        [[params.footer.links.links]]
            title = "LAN PC #5"
            url = "/article/lan-party-pc-5/"
        [[params.footer.links.links]]
            title = "LAN PC #4"
            url = "/article/lan-party-pc-4/"
        [[params.footer.links.links]]
            title = "LAN PC #3"
            url = "/article/lan-party-pc-3/"
        [[params.footer.links.links]]
            title = "LAN PC #2"
            url = "/article/lan-party-pc-2/"

        [[params.footer.links]]
            header = "Donations"
        [[params.footer.links.links]]
            title = "Moniteurs BenQ"
            url = "/article/don-etienne/"
        [[params.footer.links.links]]
            title = "PS3 et Wii"
            url = "/article/don-romain/"
        [[params.footer.links.links]]
            title = "Xbox 360"
            url = "/article/don-ryctus/"

        [[params.footer.links]]
            header = "Ailleurs"
        [[params.footer.links.links]]
            title = "Discord"
            url = "https://discord.gg/Cxy7tW4M46"
        [[params.footer.links.links]]
            title = "Twitch"
            url = "https://www.twitch.tv/fairplayersfr"
        [[params.footer.links.links]]
            title = "Mastodon"
            url = "https://piaille.fr/@fairplayers"
        [[params.footer.links.links]]
            title = "Instagram"
            url = "https://www.instagram.com/fairplayersfr"
        [[params.footer.links.links]]
            title = "Pixelfed"
            url = "https://pixelfed.fr/fairplayers"

    #     [params.footer.contact_form]
    #         enabled = true
    #         header = "Get In Touch"
    #         action = ""
