baseURL = 'http://www.fairplayers.fr'
defaultContentLanguage = "fr"
enableRobotsTXT = true
languageCode = 'fr-fr'
paginate = 10
resourceDir = "../resources"
# theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
theme = ["github.com/half-duplex/hugo-arcana"]
title = 'fairplayers'

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[taxonomies]
  category = 'categories'
  tag = 'tags'

[params]
    description = "Association de joueurs et joueuses de jeux vid√©o - Betton"
    # show_post_dates = false

    [[params.social]]
        title = "Discord"
        icon = "fa-discord"
        url = "https://discord.gg/Cxy7tW4M46"
    [[params.social]]
        title = "Instagram"
        icon = "fa-instagram"
        url = "https://www.instagram.com/fairplayersfr"
    [[params.social]]
        title = "Mastodon"
        icon = "fa-mastodon"
        url = "https://piaille.fr/@fairplayers"
    [[params.social]]
        title = "Youtube"
        icon = "fa-youtube"
        url = "https://www.youtube.com/@fairplayersfr"
    [[params.social]]
        title = "Github"
        icon = "fa-github"
        url = "https://github.com/fairplayers"

    # [params.footer]

    #     [[params.footer.links]]
    #         header = "Links to Stuff"
    #     [[params.footer.links.links]]
    #         title = "Mattis et quis rutrum"
    #         url = "#"
    #     [[params.footer.links.links]]
    #         title = "Suspendisse amet varius"
    #         url = "#"
    #     [[params.footer.links.links]]
    #         title = "Sed et dapibus quis"
    #         url = "#"

    #     [[params.footer.links]]
    #         header = "More Links to Stuff"
    #     [[params.footer.links.links]]
    #         title = "Duis neque nisi dapibus"
    #         url = "#"
    #     [[params.footer.links.links]]
    #         title = "Sed et dapibus quis"
    #         url = "#"

    #     [params.footer.contact_form]
    #         enabled = true
    #         header = "Get In Touch"
    #         action = ""
