baseURL = 'http://www.fairplayers.fr'
languageCode = 'fr-fr'
resourceDir = "../resources"
title = 'fairplayers'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

DefaultContentLanguage = "fr"
enableRobotsTXT = true
Paginate = 10
recent_posts_number = 3

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[languages]
  [languages.fr]
    weight = 2
    contentDir = "content"

[params]
  description = "Association de joueurs et joueuses de jeux vid√©o - Betton"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-purple"
  date_format = "2 January 2006"

[[params.ananke_socials]]
name = "discord"
url = "https://discord.gg/Cxy7tW4M46"

[[params.ananke_socials]]
name = "mastodon"
url = "https://piaille.fr/@fairplayers"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/fairplayers"
